### ISSUE TITLE
Vegetables and Fruits Learning Feature

### ISSUE THREAD

**Issue by vamzx** [VaibhavCodeClub/learn#21]

**Comment by hiranj-kotak** [comment]
@sapatevaibhav  i am really interested in this project. I would like to contribute to this project in many issues in this three months. Can you please assign me this and video player issue

**Comment by Rashii1218** [comment]
I am interested in this project. Can you please assign me this issue

**Comment by LEARNER-dakshesh** [comment]
Hello Vaibhav ! I wanted to work on this issue. Can you please assign me ?

**Comment by hiranj-kotak** [comment]
@sapatevaibhav  i have to create one page for fruits and vegetables or different pages

**Comment by sapatevaibhav** [comment]
Do it in single page as well keep in mind to use SVG files

**Comment by hiranj-kotak** [comment]
hey @sapatevaibhav  i am having 2 ideas in my mind for fruits and vegetable page

1) i should do same as Alphabets page pages

2) i should ask the user to guess whether it is a fruit or vegetable and on his feedback i will show the dialogbox 

please reply asap

**Comment by sapatevaibhav** [comment]
Good idea go with two just keep 2 options for each question as well keep the UI child friendly (Big and colorful buttons). cheer with green Background for correct one and red one for incorrect.
Do not make complex.

**Comment by hiranj-kotak** [comment]
hey @sapatevaibhav  i have implemented the ui part please review it and suggest some changes/ideas  so that i can improve ui 
![Screenshot_1715625642](https://github.com/VaibhavCodeClub/learn/assets/95754714/84275df6-087c-40e6-84b9-1beedc5020f8)
![Screenshot_1715625648](https://github.com/VaibhavCodeClub/learn/assets/95754714/f003adc0-0615-467b-9aac-45b17a591331)
![Screenshot_1715625653](https://github.com/VaibhavCodeClub/learn/assets/95754714/7f362158-f1e4-4927-8e24-d61abf08d969)

i have used lottie files to display correct/incorrect option

**Comment by sapatevaibhav** [comment]
Instead of showing popups just change the color of the background that will be easier.

**Comment by hiranj-kotak** [comment]
hey @sapatevaibhav  i have seen you havent mergred the pr yet 
is there anything i can do to help...

**Comment by sapatevaibhav** [comment]
> hey @sapatevaibhav i have seen you havent mergred the pr yet is there anything i can do to help...

https://github.com/VaibhavCodeClub/learn/pull/68#issuecomment-2119321199
