### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by aasthakourav20** [VaibhavCodeClub/learn#51]
Hey @VaibhavCodeClub ,  every repo has a code of conduct , please assign me this issue 

ample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by vanshikab52** [comment]
A Code_Of_Conduct.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions. It sets clear guidelines for expected behavior and helps ensure that all contributors feel safe and respected.
The repository currently lacks a CODE_OF_CONDUCT.md file which is an important resource for fostering a welcoming and inclusive environment within our community.
@sapatevaibhav  You can assign this issue to me as I'm working under GSSoC'24 as a contributor. I can add a code of conduct to this project.
Thanks

**Comment by sapatevaibhav** [comment]
@vanshikab52  -> #10
